services:
  web:  
    image: ghosted-web-app
    environment:
      - DEBUG=0
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=seng513
      - DB_PORT=3883
    ports:
     - "80:80" 